version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://s3.amazonaws.com/amazon-eks/1.27.0/2023-06-16/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
  pre_build:
    commands:
      - echo Configuring access to EKS...
      - aws eks update-kubeconfig --region ap-south-1 --name my-eks-cluster-reva
  build:
    commands:
      - echo Using NGINX version: $NGINX_VERSION
      - sed "s/\${NGINX_VERSION}/$NGINX_VERSION/g" nginx-deployment.yaml > final.yaml
      - kubectl apply -f final.yaml
