version: 0.2

env:
  variables:
    NGINX_VERSION: 1.11.10-alpine

phases:
  install:
    commands:
      - echo Installing kubectl...
      #- curl -o kubectl https://s3.amazonaws.com/amazon-eks/1.27.0/2023-06-16/bin/linux/amd64/kubectl
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.0/2024-12-20/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
     # - mv ./kubectl /usr/local/bin/
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
  pre_build:
    commands:
      - echo Configuring access to EKS...
      - aws eks update-kubeconfig --region ap-south-1 --name my-eks-cluster-reva
  build:
    commands:
     # - echo using Nginx Version: $NGINX_VERSION
      - sed "s/\${NGINX_VERSION}/$NGINX_VERSION/g" nginx-deployment.yaml
     # - vi final.yaml
      - sed -i 's/\r$//' nginx-deployment.yaml
     # - vi final.yaml
      - kubectl apply -f nginx-deployment.yaml
